import { BuyoutSummary } from "@/lib/types";
import { buildWorkflow } from "@/lib/workflows";

export const mockBuyouts: BuyoutSummary[] = [
  {
    id: "bo_sarah_chen",
    name: "Sarah Chen",
    eventType: "Birthday",
    statusLabel: "Awaiting Sign-Ups",
    sourceStatusLabel: "Awaiting Sign-Ups",
    eventDate: "2026-04-15",
    countdownDays: 19,
    location: "1583 Decatur",
    assignedTo: "Autumn",
    instructor: "Autumn",
    lifecycleStage: "Sign-Ups",
    sourceLifecycleStage: "Sign-Ups",
    lifecycleStep: 7,
    trackingHealth: "On track",
    sourceTrackingHealth: "On track",
    ballInCourt: "Client",
    sourceBallInCourt: "Client",
    nextAction: "Check on fill",
    sourceNextAction: "Check on fill",
    daysWaiting: 3,
    lastAction: "2026-03-24",
    signups: 12,
    capacity: 20,
    signupFillPercent: 60,
    total: 1200,
    amountPaid: 600,
    outstanding: 600,
    paymentProgress: 50,
    numberOfHours: 1.5,
    clientName: "Sarah Chen",
    clientEmail: "sarah@example.com",
    clientPhone: "(404) 555-0112",
    startTime: "2:00 PM",
    endTime: "3:30 PM",
    preferredLocation: "1583 Decatur",
    depositAmount: 600,
    depositLink: "https://pay.tsp.com/dep-sc",
    balanceLink: "https://pay.tsp.com/bal-sc",
    signupLink: "https://momence.com/tsp/sc",
    notes: "Client wants light food and champagne guidance.",
    healthFlags: [],
    sentTemplateIds: ["t1", "t3", "t5"],
    workflowProgress: 63,
    workflow: buildWorkflow([
      "inquiry-reviewed",
      "initial-response",
      "follow-up",
      "feasibility",
      "quote",
      "deposit-requested",
      "deposit-received",
      "details-confirmed",
      "signup-link-created",
      "signup-link-sent"
    ])
  },
  {
    id: "bo_mike_torres",
    name: "Mike Torres",
    eventType: "Corporate",
    statusLabel: "Deposit Received",
    sourceStatusLabel: "Deposit Received",
    eventDate: "2026-04-08",
    countdownDays: 12,
    location: "763 Trabert",
    assignedTo: "Kelly",
    instructor: "Unassigned",
    lifecycleStage: "Deposit",
    sourceLifecycleStage: "Deposit",
    lifecycleStep: 5,
    trackingHealth: "At risk",
    sourceTrackingHealth: "At risk",
    ballInCourt: "Team",
    sourceBallInCourt: "Team",
    nextAction: "Secure instructor",
    sourceNextAction: "Secure instructor",
    daysWaiting: 5,
    lastAction: "2026-03-22",
    signups: 0,
    capacity: 30,
    signupFillPercent: 0,
    total: 2400,
    amountPaid: 1200,
    outstanding: 1200,
    paymentProgress: 50,
    numberOfHours: 2,
    clientName: "Mike Torres",
    clientEmail: "mike.t@corp.com",
    clientPhone: "(404) 555-0234",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    preferredLocation: "763 Trabert",
    depositAmount: 1200,
    depositLink: "https://pay.tsp.com/dep-mt",
    balanceLink: "https://pay.tsp.com/bal-mt",
    signupLink: "",
    notes: "Corporate team event. Instructor assignment is still open.",
    healthFlags: ["Instructor is still unassigned."],
    sentTemplateIds: ["t1", "t3"],
    workflowProgress: 38,
    workflow: buildWorkflow([
      "inquiry-reviewed",
      "initial-response",
      "feasibility",
      "quote",
      "deposit-requested",
      "deposit-received"
    ])
  },
  {
    id: "bo_jenna_woodall",
    name: "Jenna Woodall",
    eventType: "Bachelorette",
    statusLabel: "Final Confirmation Sent",
    sourceStatusLabel: "Final Confirmation Sent",
    eventDate: "2026-04-02",
    countdownDays: 6,
    location: "1581 Decatur",
    assignedTo: "Autumn",
    instructor: "Morgan",
    lifecycleStage: "Final",
    sourceLifecycleStage: "Final",
    lifecycleStep: 9,
    trackingHealth: "On track",
    sourceTrackingHealth: "On track",
    ballInCourt: "Client",
    sourceBallInCourt: "Client",
    nextAction: "Final attendance check",
    sourceNextAction: "Final attendance check",
    daysWaiting: 1,
    lastAction: "2026-03-26",
    signups: 15,
    capacity: 15,
    signupFillPercent: 100,
    total: 900,
    amountPaid: 900,
    outstanding: 0,
    paymentProgress: 100,
    numberOfHours: 1.5,
    clientName: "Jenna Woodall",
    clientEmail: "jenna.w@gmail.com",
    clientPhone: "(770) 555-0389",
    startTime: "6:00 PM",
    endTime: "7:30 PM",
    preferredLocation: "1581 Decatur",
    depositAmount: 900,
    depositLink: "",
    balanceLink: "",
    signupLink: "https://momence.com/tsp/jw",
    notes: "Fully paid and nearly complete. Final confirmation has been sent.",
    healthFlags: [],
    sentTemplateIds: ["t1", "t3", "t5", "t11"],
    workflowProgress: 75,
    workflow: buildWorkflow([
      "inquiry-reviewed",
      "initial-response",
      "feasibility",
      "quote",
      "deposit-requested",
      "deposit-received",
      "details-confirmed",
      "signup-link-created",
      "signup-link-sent",
      "signups-monitored",
      "final-payment",
      "final-confirmation"
    ])
  }
];
